export const MessageType = {
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    DISCONNECTED: "DISCONNECTED",
    REQUEST: "REQUEST",
    LEAVE: "LEAVE",
    OFFER: "OFFER",
    ANSWER: "ANSWER",
    CANDIDATE: "CANDIDATE"
};